// Mocks generated by Mockito 5.3.2 from annotations
// in movies_api/test/features/home_page/data/datasources/api_repository_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movies_api/features/home_page/data/datasources/api_repository_remote_data_source.dart'
    as _i6;
import 'package:movies_api/features/home_page/data/models/config_model.dart'
    as _i3;
import 'package:movies_api/features/home_page/data/models/movie_model.dart'
    as _i4;
import 'package:movies_api/features/home_page/data/models/trending_model.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfigModel_1 extends _i1.SmartFake implements _i3.ConfigModel {
  _FakeConfigModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMovieModel_2 extends _i1.SmartFake implements _i4.MovieModel {
  _FakeMovieModel_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTrendingModel_3 extends _i1.SmartFake implements _i5.TrendingModel {
  _FakeTrendingModel_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiRepositoryRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiRepositoryRemoteDataSourceImpl extends _i1.Mock
    implements _i6.ApiRepositoryRemoteDataSourceImpl {
  MockApiRepositoryRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get key => (super.noSuchMethod(
        Invocation.getter(#key),
        returnValue: '',
      ) as String);
  @override
  _i2.Response get response => (super.noSuchMethod(
        Invocation.getter(#response),
        returnValue: _FakeResponse_0(
          this,
          Invocation.getter(#response),
        ),
      ) as _i2.Response);
  @override
  set response(_i2.Response? _response) => super.noSuchMethod(
        Invocation.setter(
          #response,
          _response,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i7.Future<_i3.ConfigModel> getConfigurationApi() => (super.noSuchMethod(
        Invocation.method(
          #getConfigurationApi,
          [],
        ),
        returnValue: _i7.Future<_i3.ConfigModel>.value(_FakeConfigModel_1(
          this,
          Invocation.method(
            #getConfigurationApi,
            [],
          ),
        )),
      ) as _i7.Future<_i3.ConfigModel>);
  @override
  _i7.Future<_i4.MovieModel> getPopularMovies() => (super.noSuchMethod(
        Invocation.method(
          #getPopularMovies,
          [],
        ),
        returnValue: _i7.Future<_i4.MovieModel>.value(_FakeMovieModel_2(
          this,
          Invocation.method(
            #getPopularMovies,
            [],
          ),
        )),
      ) as _i7.Future<_i4.MovieModel>);
  @override
  _i7.Future<_i5.TrendingModel> getTrendingApi() => (super.noSuchMethod(
        Invocation.method(
          #getTrendingApi,
          [],
        ),
        returnValue: _i7.Future<_i5.TrendingModel>.value(_FakeTrendingModel_3(
          this,
          Invocation.method(
            #getTrendingApi,
            [],
          ),
        )),
      ) as _i7.Future<_i5.TrendingModel>);
}
